import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-music-neighboring-rights-royalty-recovery",
  "engine": "recovery",
  "title": "Music Neighboring Rights Royalty Recovery",
  "shortTitle": "Music Neighboring Rights Royalty Recovery",
  "tagline": "Identify unmatched recordings and recover neighboring-rights royalties across performers, masters, societies, and territories.",
  "industry": "Music Rights Revenue Assurance",
  "buyer": "Labels, performers, and neighboring-rights administrators",
  "uiPort": 4738,
  "apiPort": 5738,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Music Neighboring Rights Royalty Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments in one accountable workflow. Identify unmatched recordings and recover neighboring-rights royalties across performers, masters, societies, and territories.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Music Neighboring Rights Royalty Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("recording-metadata-registry","MNR01","Recording metadata registry","Execute recording metadata registry using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed recording metadata registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Recording metadata registry Reference","text","MNR01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("isrc-normalization","MNR02","ISRC normalization","Execute isrc normalization using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed isrc normalization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","ISRC normalization Reference","text","MNR02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("performer-lineup-evidence","MNR03","Performer lineup evidence","Execute performer lineup evidence using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed performer lineup evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Performer lineup evidence Reference","text","MNR03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("rights-ownership-mapping","MNR04","Rights ownership mapping","Execute rights ownership mapping using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed rights ownership mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Rights ownership mapping Reference","text","MNR04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("airplay-usage-ingestion","MNR05","Airplay usage ingestion","Execute airplay usage ingestion using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed airplay usage ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Airplay usage ingestion Reference","text","MNR05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("public-performance-matching","MNR06","Public performance matching","Execute public performance matching using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed public performance matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Public performance matching Reference","text","MNR06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("simulcast-usage-control","MNR07","Simulcast usage control","Execute simulcast usage control using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed simulcast usage control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Simulcast usage control Reference","text","MNR07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("territory-eligibility-rules","MNR08","Territory eligibility rules","Execute territory eligibility rules using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed territory eligibility rules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Territory eligibility rules Reference","text","MNR08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("featured-performer-allocation","MNR09","Featured performer allocation","Execute featured performer allocation using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed featured performer allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Featured performer allocation Reference","text","MNR09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("non-featured-performer-allocation","MNR10","Non-featured performer allocation","Execute non-featured performer allocation using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed non-featured performer allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Non-featured performer allocation Reference","text","MNR10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("society-statement-matching","MNR11","Society statement matching","Execute society statement matching using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed society statement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Society statement matching Reference","text","MNR11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("unmatched-usage-claim","MNR12","Unmatched usage claim","Execute unmatched usage claim using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed unmatched usage claim decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Unmatched usage claim Reference","text","MNR12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("society-query-workflow","MNR13","Society query workflow","Execute society query workflow using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed society query workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Society query workflow Reference","text","MNR13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("cash-reconciliation","MNR14","Cash reconciliation","Execute cash reconciliation using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Cash reconciliation Reference","text","MNR14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]}),
feature("recording-territory-analytics","MNR15","Recording territory analytics","Execute recording territory analytics using recording metadata, performer lineups, ISRCs, airplay, simulcast, public performance, territory rules, society statements, claims, and payments.","Produce a governed recording territory analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recording / Territory","text","Recording / Territory · Standard Case"],["caseReference","Recording territory analytics Reference","text","MNR15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1813750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2194638],["domainDriver","Right Type","select","Featured performer",["Featured performer","Non-featured performer","Master owner"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recording metadata registry case","ISRC normalization case","Performer lineup evidence case","Rights ownership mapping case","Airplay usage ingestion case"]})
]);
